# Generated by Django 4.1 on 2022-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('coordinator', models.CharField(max_length=200)),
                ('POCEmail', models.EmailField(default='deanbsa@iitd.ac.in', max_length=200)),
            ],
        ),
    ]
