# Generated by Django 4.1 on 2022-08-31 10:23

from django.db import migrations, models
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbook',
            name='bookingDate',
            field=models.DateField(validators=[sport.models.is_future_date]),
        ),
    ]
