# Generated by Django 4.1 on 2022-09-01 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_alter_slotbook_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'DAILY'), ('Weekly', 'WEEKLY'), ('Monthly', 'MONTHLY'), ('Yearly', 'YEARLY')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sport.sport'),
            preserve_default=False,
        ),
    ]
