# Generated by Django 4.1 on 2022-09-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_alter_slot_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.facility'),
        ),
    ]
