# Generated by Django 4.1 on 2022-09-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_alter_slot_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbook',
            name='type',
            field=models.CharField(choices=[('Daily', 'DAILY'), ('Weekly', 'WEEKLY'), ('Monthly', 'MONTHLY'), ('Yearly', 'YEARLY')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
