# Generated by Django 4.1 on 2022-09-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_slotbook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='timeEnd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='timeStart',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slotbook',
            name='type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20),
        ),
    ]
