# Generated by Django 4.1 on 2022-09-02 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0011_alter_slot_frequency_alter_slot_timeend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='frequency',
        ),
        migrations.AddField(
            model_name='slot',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[sport.models.is_future_date]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
