# Generated by Django 4.1 on 2022-09-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0012_remove_slot_frequency_slot_booked_at_slot_booked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[sport.models.less_than_six])),
                ('review', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SlotBook',
        ),
        migrations.AddField(
            model_name='review',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.slot'),
        ),
    ]
